version: '3.9'

services:

  shareyourcloning_frontend_dev:
    container_name: shareyourcloning_frontend_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
